[[plugins]]
repo = 'Shougo/dein.vim'

# deoplete ---------------

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
    let g:deoplete#enable_at_startup = 1
    set completeopt+=noinsert
    inoremap <expr><C-j> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
            \ "\<Plug>(neosnippet_expand_or_jump)" : "\<C-j>"
    inoremap <expr><C-k> pumvisible() ? "\<C-p>" :
        \ neosnippet#expandable_or_jumpable() ?
            \ "\<Plug>(neosnippet_expand_or_jump)" : "\<C-k>"
    inoremap <expr><CR> pumvisible() ? deoplete#close_popup() : "\<CR>"
'''

# neosnippet ---------------

[[plugins]]
repo = 'Shougo/neosnippet'
hook_add = '''
    imap <tab>     <Plug>(neosnippet_expand_or_jump)
    smap <tab>     <Plug>(neosnippet_expand_or_jump)
    xmap <tab>     <Plug>(neosnippet_expand_target)
    if has('conceal')
    set conceallevel=2 concealcursor=niv
    endif
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# colorscheme ---------------

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    set laststatus=2
'''

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
    syntax on
    colorscheme iceberg
'''

# misc ---------------

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
    set helplang=ja,en
'''

[[plugins]]
repo = 'thinca/vim-zenspace'
hook_add = '''
    let g:zenspace#default_mode = 'on'
'''
