[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
hook_add = '''
    NeoCompleteEnable
'''

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
    syntax on
    colorscheme iceberg
'''

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
    set helplang=ja,en
'''
